/**
 * Validated write-back for `.harness-align` sources used by the desktop shell and tests.
 * Encode and validate before `atomicWrite`. Multi-file updates are not a single disk transaction.
 */

import { promises as fs } from "node:fs";
import { join, posix, resolve } from "node:path";
import { tmpdir } from "node:os";
import { stringify as stringifyYaml } from "yaml";
import { assertContained, assertNoReparseTree, atomicWrite, display, ensureRegularSource, isAtomicWriteTemporary, lstatIfExists, pathKey, reparseError, resolveUserHome } from "./FsSafe.js";
import { loadAgents, loadConfig, loadLayerOptions, loadRules, loadSharedRules, type SharedRule, validateAgentHarnesses, validateConfig, validateTargets } from "./Load.js";
import {
    IDENTIFIER_NAME,
    type Agent,
    assertWindowsSafeName,
    codePointCompare,
    type Config,
    errorText,
    type Harness,
    type HarnessConfig,
    HalignError,
    isRecord,
    type LayerOption,
    type Metadata,
    normalizedBody,
    type ProjectSkill,
    type Rule,
    valueText,
} from "./Model.js";
import { loadSkills, parseGitHubSkillSource } from "./Skills.js";
import { parseSyncSnapshot, readSyncSnapshot, syncSkillIndex, syncSnapshotHash, type SyncSnapshot } from "./Sync.js";

/** Default `.harness-align/config.json` written when the user workspace does not exist yet. */
const DEFAULT_USER_CONFIG = {
    version: 1,
    name: "AGENTS",
    layers: [],
    harnesses: [
        { name: "codex", config_path: ".codex", agent_format: "toml", agent_extension: "toml", instructions_field: "developer_instructions" },
        { name: "cursor", config_path: ".cursor", agent_format: "yaml", agent_extension: "md" },
        { name: "opencode", config_path: ".config/opencode", agent_format: "yaml", agent_extension: "md" },
    ],
};

/** Ownership marker for the automatically refreshed workspace guide. */
const WORKSPACE_GUIDE_MARKER = "<!-- Generated by Harness Align. Do not edit. -->";

/** Concise configuration instructions bundled with the application. */
const WORKSPACE_GUIDE = `${WORKSPACE_GUIDE_MARKER}
# Harness Align 配置目录

## 目录

- [目录结构](#目录结构)
- [生成与部署关系](#生成与部署关系)
- [修改方式](#修改方式)

## 目录结构

\`.harness-align/\` 是 Harness Align 的用户配置源目录. Harness 指 Codex, Cursor 等编码助手; 本目录统一维护它们的规则, 子代理配置和 Skills.

| 路径 | 内容与作用 | 是否可直接修改 |
| --- | --- | --- |
| \`config.json\` | 总配置: 版本 \`version: 1\`, 输出标题 \`name\`, 有序 \`layers\` 选择, \`harnesses\` 的名称/部署路径/子代理格式, 可选 Skills 上游仓库 \`skill_sources\`. | 可以, 保持版本和字段约束. |
| \`rules/**/*.md\` (排除 \`shared/\`) | 组成助手 AGENTS.md 的规则片段. YAML frontmatter 指定非负整数 \`priority\` 和 \`targets\`, Markdown 正文是实际规则. | 可以. |
| \`rules/shared/**/*.md\` | 供规则按需引用的独立共享文档, 不拼入助手 AGENTS.md. | 可以. |
| \`layers/<layer>/<option>.md\` | 可切换的规则片段. config.json 的 \`layers\` 决定组顺序, \`selected\` 决定每组采用哪个选项; frontmatter 仅支持 \`targets\`. | 可以. |
| \`agents/*.md\` | 子代理 (Subagent) 配置源. YAML frontmatter 保存 \`name\`, \`description\`, \`harnesses\` 下各助手的原生 metadata; Markdown 正文保存共享的子代理指令. | 可以. |
| \`skills/<id>/SKILL.md\` 及同目录资源 | 可复用技能的说明, 脚本和参考资料. | 本地或无来源记录的 Skill 可以; GitHub 来源的 Skill 不直接修改. |
| \`skills/index.json\` | 应用维护的 Skill 来源记录, 可读取对应 id 的 \`origin\` 判断来源. | 不可以, 不手改来源或哈希. |
| \`generated/<harness>/AGENTS.md\` | 为该助手拼装好的完整规则文档. | 不可以, 修改对应 Rules / Layer 源文件. |
| \`generated/<harness>/agents/\` | 为该助手转换格式后的子代理配置, 格式和扩展名由 config.json 决定. | 不可以, 修改 \`agents/*.md\` 配置源. |
| \`generated/.manifest.json\` | 应用管理的生成文件清单. | 不可以; 整个 \`generated/\` 均不手改. |
| \`AGENTS.md\` | 当前配置目录的自动生成指引, 不参与助手规则拼装, 部署或同步. | 不可以, 应用自动更新. |
| \`.sync-backup.json\`, \`.sync-recovery.json\` | 同步时产生的本机备份和中断恢复记录, 由应用管理. | 不可以. |

## 生成与部署关系

- 规则文档: 根 Rules 按 \`priority\` 升序排列, 同优先级按路径排序, 再追加按配置顺序选中的 Layer 正文; 各片段按 \`targets\` 筛选后拼成 \`generated/<harness>/AGENTS.md\`.
- 子代理配置: \`agents/*.md\` 按其 \`harnesses\` 键选择输出助手, 将共享指令和对应 metadata 转成该助手要求的 TOML 或 YAML frontmatter + Markdown 文件, 写入 \`generated/<harness>/agents/\`.
- 部署: 生成的规则文档和子代理配置写入用户主目录下对应的 \`config_path\`; 共享规则复制到 \`~/.agents/shared-rules/\`, Skills 按 id 复制到 \`~/.agents/skills/\`.

## 修改方式

- 按上表的可编辑范围修改配置源, 先读 \`config.json\` 和现有同类文件, 保持现有格式及 UTF-8 without BOM, LF. 标为不可修改的文件也不手工创建, 删除或重命名. 需要定制 GitHub Skill 时, 使用新 id 建立本地 Skill, 保留原来源记录.
- Rule / Layer 的 \`targets\` 必须显式列出目标 Harness 名称, 省略或空数组均不生效. 名称引用大小写须一致; 重命名时更新相关 \`targets\`, 子代理 \`harnesses\` 键和 Layer 选择.
- 配置源修改不会立即改变助手已部署的配置. 完成后说明改了哪些源文件及影响, 由用户通过 Harness Align 的 Generate / Setup 生成和部署; 不要求当前 Agent 操作 GUI. 此目录没有 CLI 或 npm 项目.

详细格式与约束见 [Harness Align 项目 README](https://github.com/SnowyLake/HarnessAlign#readme), 必要时查阅仓库 \`src/engine/\` 源码.
`;

/** Loaded `.harness-align` workspace for the desktop editor and tests. */
export interface Workspace
{
    config: Config;
    rootRules: Rule[];
    layerOptions: Record<string, LayerOption[]>;
    sharedRules: SharedRule[];
    agents: Agent[];
    skills: ProjectSkill[];
}

/** Editor payload for creating or updating a rule source file. */
export type RuleInput = Rule;

/** Editor payload for creating or updating a layer option source file. */
export type LayerOptionInput = Pick<LayerOption, "path" | "targets" | "body">;

/** Sort editable rules by priority and use their paths as a deterministic tie-breaker. */
function sortEditableRules(rules: Rule[]): Rule[]
{
    return rules.slice().sort((left, right) => left.priority - right.priority || codePointCompare(left.path, right.path));
}

/** Build the JSON document written to `config.json`. */
function configDocument(config: Config): Record<string, unknown>
{
    const document: Record<string, unknown> = {
        version: 1,
        name: config.name,
        layers: config.layers.map((layer) => ({ name: layer.name, selected: layer.selected })),
        harnesses: config.harnesses.map((harness) =>
        {
            const item: Record<string, unknown> = {
                name: harness.name,
                config_path: harness.configPath,
                agent_format: harness.agentFormat,
                agent_extension: harness.agentExtension,
            };
            if (harness.instructionsField !== undefined) item.instructions_field = harness.instructionsField;
            return item;
        }),
    };
    if (config.skillSources.length > 0)
    {
        document.skill_sources = config.skillSources.map((source) => ({
            owner: source.owner,
            name: source.name,
            branch: source.branch,
        }));
    }
    return document;
}

/** Normalize and contain a managed `.harness-align` relative path. */
function managedRelative(value: string, label: string): string
{
    if (!value || value.includes("\\") || posix.isAbsolute(value) || /^[A-Za-z]:/u.test(value))
    {
        throw new HalignError(`${label}: path must stay inside .harness-align, got ${valueText(value)}`);
    }
    const parts = value.split("/");
    if (parts.some((part) => !part || part === "." || part === ".."))
    {
        throw new HalignError(`${label}: path must stay inside .harness-align, got ${valueText(value)}`);
    }
    for (const part of parts) assertWindowsSafeName(part, label);
    if (value === ".harness-align/generated" || value.startsWith(".harness-align/generated/"))
    {
        throw new HalignError(`${label}: path must stay inside managed .harness-align sources, got ${valueText(value)}`);
    }
    if (value !== ".harness-align/config.json" && !value.startsWith(".harness-align/rules/") && !value.startsWith(".harness-align/layers/") && !value.startsWith(".harness-align/agents/") && !value.startsWith(".harness-align/skills/"))
    {
        throw new HalignError(`${label}: path must stay inside managed .harness-align sources, got ${valueText(value)}`);
    }
    return value;
}

/** Resolve a managed source path and ensure it stays inside the config root. */
async function resolveManaged(root: string, relativePath: string, label: string): Promise<string>
{
    const relative = managedRelative(relativePath, label);
    const path = resolve(root, ...relative.split("/"));
    assertContained(root, path, label);
    await ensureRegularSource(root, path);
    return path;
}

/** Reject another existing rename target while allowing the source's own filesystem alias. */
async function assertRenameDestination(source: string, destination: string, label: string): Promise<void>
{
    if (pathKey(source) !== pathKey(destination) && await lstatIfExists(destination)) throw new HalignError(`${label}: destination already exists`);
}

/** Atomically write a managed source file after reparse checks. */
async function writeManaged(root: string, relativePath: string, content: Buffer): Promise<void>
{
    const path = await resolveManaged(root, relativePath, relativePath);
    const existing = await lstatIfExists(path);
    if (existing?.isSymbolicLink()) throw reparseError(root, path, false);
    if (existing && !existing.isFile()) throw new HalignError(`${relativePath}: managed source must be a file`);
    await atomicWrite(path, content);
}

/** Preflight a source batch and restore completed writes if a later write fails. */
async function writeManagedBatch(root: string, writes: Array<{ path: string; content: Buffer }>): Promise<void>
{
    const prepared = await Promise.all(writes.map(async (write) => ({
        ...write,
        original: await fs.readFile(await resolveManaged(root, write.path, write.path)),
    })));
    const written: typeof prepared = [];
    try
    {
        for (const write of prepared)
        {
            await writeManaged(root, write.path, write.content);
            written.push(write);
        }
    }
    catch (error)
    {
        const failures: string[] = [];
        for (const write of written.reverse())
        {
            try
            {
                await writeManaged(root, write.path, write.original);
            }
            catch (rollbackError)
            {
                failures.push(`${write.path}: ${errorText(rollbackError)}`);
            }
        }
        if (failures.length > 0) throw new HalignError(`Source update failed: ${errorText(error)}; rollback failed: ${failures.join("; ")}`);
        throw error;
    }
}

/** Serialize YAML frontmatter plus a markdown body. */
function serializeFrontmatter(metadata: Record<string, unknown>, body: string, path: string): Buffer
{
    const markdown = normalizedBody(body);
    if (!markdown.trim()) throw new HalignError(`${path}: Markdown body must be non-empty, got ${valueText(body)}`);
    const yamlText = stringifyYaml(metadata, { lineWidth: 0, sortMapEntries: false }).trimEnd();
    return Buffer.from(`---\n${yamlText}\n---\n\n${markdown}`, "utf8");
}

/** Serialize layer targets plus a possibly empty Markdown body. */
function serializeLayerOption(targets: string[], body: string): Buffer
{
    const markdown = body.trim() ? normalizedBody(body) : "";
    const yamlText = stringifyYaml({ targets }, { lineWidth: 0, sortMapEntries: false }).trimEnd();
    return Buffer.from(`---\n${yamlText}\n---\n\n${markdown}`, "utf8");
}

/** Require a rule path under the expected `.harness-align` subtree. */
function assertRulePath(path: string, kind: "root" | "shared"): void
{
    if (!path.endsWith(".md")) throw new HalignError(`${path}: rule path must end with .md`);
    const comparison = process.platform === "win32" ? path.toLowerCase() : path;
    if (kind === "root" && (comparison.startsWith(".harness-align/rules/shared/") || !comparison.startsWith(".harness-align/rules/")))
    {
        throw new HalignError(`${path}: root rule path must stay under .harness-align/rules and outside shared`);
    }
    if (kind === "shared" && !comparison.startsWith(".harness-align/rules/shared/"))
    {
        throw new HalignError(`${path}: shared rule path must stay under .harness-align/rules/shared`);
    }
}

/** Classify a root or shared rule path. */
function ruleKind(path: string): "root" | "shared"
{
    const comparison = process.platform === "win32" ? path.toLowerCase() : path;
    if (comparison.startsWith(".harness-align/rules/shared/")) return "shared";
    return "root";
}

/** Classify editable rule and agent source paths. */
function editableSourceKind(path: string): "root-rule" | "shared-rule" | "agent" | undefined
{
    if (path.startsWith(".harness-align/agents/")) return "agent";
    if (ruleKind(path) === "shared") return "shared-rule";
    if (path.startsWith(".harness-align/rules/")) return "root-rule";
    return undefined;
}

/** Return whether a discovered layer directory exists. */
function hasCatalogLayer(options: Record<string, LayerOption[]>, name: string): boolean
{
    return Object.hasOwn(options, name);
}

/** Return whether any catalog layer matches `name` without case sensitivity. */
function catalogHasFoldedName(options: Record<string, LayerOption[]>, name: string): boolean
{
    const folded = name.toLowerCase();
    return Object.keys(options).some((existing) => existing.toLowerCase() === folded);
}

/** Require a direct option path under one layer directory. */
function layerOptionParts(path: string): { layer: string; option: string }
{
    const match = /^\.harness-align\/layers\/([^/]+)\/([^/]+)\.md$/u.exec(path);
    if (!match || !IDENTIFIER_NAME.test(match[1]!) || !IDENTIFIER_NAME.test(match[2]!))
    {
        throw new HalignError(`${path}: layer option path must match .harness-align/layers/<layer>/<option>.md`);
    }
    return { layer: match[1]!, option: match[2]! };
}

/** Require a subagent path under `.harness-align/agents`. */
function assertAgentPath(path: string): void
{
    if (!/^\.harness-align\/agents\/[^/]+\.md$/u.test(path))
    {
        throw new HalignError(`${path}: agent path must be a Markdown file directly under .harness-align/agents`);
    }
}

/** Validate a subagent payload before writing it. */
function assertAgentInput(agent: Agent, harnesses: HarnessConfig[]): void
{
    assertAgentPath(agent.path);
    if (!agent.name.trim() || !IDENTIFIER_NAME.test(agent.name))
    {
        throw new HalignError(`${agent.path}: name must match ${IDENTIFIER_NAME.source}, got ${valueText(agent.name)}`);
    }
    assertWindowsSafeName(agent.name, agent.path);
    if (!agent.description.trim())
    {
        throw new HalignError(`${agent.path}: description must be a non-empty string, got ${valueText(agent.description)}`);
    }
    validateAgentHarnesses(agent.harnesses, agent.path, harnesses);
}

/** Load config, root rules, layer options, shared-rules, agents, and skills from a config root. */
export async function loadWorkspace(rootPath: string): Promise<Workspace>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const [agents, rules, layerOptions, sharedRules, skills] = await Promise.all([
        loadAgents(root, config.harnesses),
        loadRules(root, config.harnesses),
        loadLayerOptions(root, config),
        loadSharedRules(root),
        loadSkills(root),
    ]);
    return { config, rootRules: sortEditableRules(rules), layerOptions, sharedRules, agents, skills };
}

/** Materialize only snapshot-managed paths, preserving generated output and unrelated root files. */
async function replaceSyncSources(root: string, before: SyncSnapshot, after: SyncSnapshot): Promise<void>
{
    const sourceRoot = join(root, ".harness-align");
    await ensureRegularSource(root, sourceRoot);
    for (const path of [...Object.keys(before.files), ...Object.keys(after.files), ...before.directories, ...after.directories])
    {
        await ensureRegularSource(root, join(sourceRoot, ...path.split("/")));
    }
    for (const path of Object.keys(before.files))
    {
        if (!Object.hasOwn(after.files, path)) await fs.unlink(join(sourceRoot, ...path.split("/")));
    }
    for (const path of before.directories.filter((path) => !after.directories.includes(path)).sort((a, b) => b.length - a.length))
    {
        const directory = join(sourceRoot, ...path.split("/"));
        for (const entry of await fs.readdir(directory, { withFileTypes: true }))
        {
            if (!entry.isFile() || !isAtomicWriteTemporary(entry.name)) continue;
            const temporary = join(directory, entry.name);
            await ensureRegularSource(root, temporary);
            await fs.unlink(temporary);
        }
        await fs.rmdir(directory);
    }
    for (const path of after.directories) await fs.mkdir(join(sourceRoot, ...path.split("/")), { recursive: true });
    for (const [path, content] of Object.entries(after.files))
    {
        await writeManaged(root, `.harness-align/${path}`, Buffer.from(content, "base64"));
    }
}

/** Validate a complete source candidate in an isolated temporary workspace before changing live data. */
export async function validateSyncSources(snapshot: SyncSnapshot, allowRemoteSkills = false): Promise<void>
{
    const checked = parseSyncSnapshot(snapshot);
    if (allowRemoteSkills && checked.files["skills/index.json"] !== undefined)
    {
        const index = syncSkillIndex(checked);
        for (const [id, entry] of Object.entries(index))
        {
            if (entry.origin === "github" && !Object.keys(checked.files).some((path) => path.startsWith(`skills/${id}/`))
                && !checked.directories.some((path) => path === `skills/${id}` || path.startsWith(`skills/${id}/`))) delete index[id];
        }
        checked.files["skills/index.json"] = Buffer.from(JSON.stringify({ skills: index })).toString("base64");
    }
    const staging = await fs.mkdtemp(join(tmpdir(), "halign-sync-"));
    try
    {
        await replaceSyncSources(staging, { version: 1, files: {}, directories: [] }, checked);
        await loadWorkspace(staging);
    }
    finally
    {
        assertContained(tmpdir(), staging, "sync validation cleanup");
        await assertNoReparseTree(staging, staging);
        await fs.rm(staging, { recursive: true, force: true });
    }
}

/** Resolve a local recovery record without accepting a renderer-selected path. */
async function syncRecordPath(root: string, name: ".sync-recovery.json" | ".sync-backup.json"): Promise<string>
{
    const path = join(root, ".harness-align", name);
    await ensureRegularSource(root, path);
    const stats = await lstatIfExists(path);
    if (stats && !stats.isFile()) throw new HalignError(`${path}: expected a regular sync recovery file`);
    return path;
}

/** Restore an interrupted source update, refusing to discard edits made outside that update. */
export async function recoverSyncSources(root: string): Promise<void>
{
    const journalPath = await syncRecordPath(root, ".sync-recovery.json");
    const stats = await lstatIfExists(journalPath);
    if (!stats) return;
    if (stats.size > 96 * 1024 * 1024) throw new HalignError(`${journalPath}: recovery record exceeds 96 MiB`);
    try
    {
        const journal: unknown = JSON.parse(await fs.readFile(journalPath, "utf8"));
        if (!isRecord(journal) || journal.version !== 1) throw new HalignError(`${journalPath}: expected recovery version 1`);
        const before = parseSyncSnapshot(journal.before);
        const after = parseSyncSnapshot(journal.after);
        const current = await readSyncSnapshot(root);
        for (const path of new Set([...Object.keys(current.files), ...Object.keys(before.files), ...Object.keys(after.files)]))
        {
            const value = current.files[path];
            if (value !== before.files[path] && value !== after.files[path])
            {
                throw new HalignError(`sync file ${path}: changed outside the interrupted update; preserve that edit before retrying recovery`);
            }
        }
        for (const path of new Set([...current.directories, ...before.directories, ...after.directories]))
        {
            const exists = current.directories.includes(path);
            if (exists !== before.directories.includes(path) && exists !== after.directories.includes(path)) throw new HalignError(`sync directory ${path}: changed outside the interrupted update`);
        }
        await replaceSyncSources(root, current, before);
        await fs.unlink(journalPath);
    }
    catch (error)
    {
        throw new HalignError(`sync recovery failed; original data remains in ${journalPath}: ${errorText(error)}`);
    }
}

/** Apply a validated full source snapshot with a persistent rollback record and stale-preview guard. */
export async function applySyncSources(root: string, expected: SyncSnapshot, snapshot: SyncSnapshot): Promise<void>
{
    await recoverSyncSources(root);
    const next = parseSyncSnapshot(snapshot);
    await validateSyncSources(next);
    const before = await readSyncSnapshot(root);
    if (syncSnapshotHash(before) !== syncSnapshotHash(expected)) throw new HalignError("sync: local sources changed; preview again before applying");
    if (syncSnapshotHash(before) === syncSnapshotHash(next)) return;
    const journalPath = await syncRecordPath(root, ".sync-recovery.json");
    const backupPath = await syncRecordPath(root, ".sync-backup.json");
    await atomicWrite(backupPath, Buffer.from(`${JSON.stringify(before)}\n`));
    await atomicWrite(journalPath, Buffer.from(`${JSON.stringify({ version: 1, before, after: next })}\n`));
    try
    {
        await replaceSyncSources(root, before, next);
        await loadWorkspace(root);
        await fs.unlink(journalPath);
    }
    catch (error)
    {
        await recoverSyncSources(root);
        throw new HalignError(`sync source update rolled back; backup: ${backupPath}: ${errorText(error)}`);
    }
}

/** Initialize the fixed workspace and its guide, migrating legacy data only when the destination is absent. */
export async function ensureUserWorkspace(userProfile = process.env.USERPROFILE): Promise<string>
{
    const root = resolveUserHome(userProfile);
    const homeStats = await lstatIfExists(root);
    if (!homeStats) throw new HalignError(`USERPROFILE must be an existing directory, got ${valueText(root)}`);
    if (homeStats.isSymbolicLink()) throw reparseError(root, root, false);
    if (!homeStats.isDirectory()) throw new HalignError(`USERPROFILE must be a directory, got ${valueText(root)}`);
    const halign = join(root, ".harness-align");
    const stats = await lstatIfExists(halign);
    if (stats?.isSymbolicLink()) throw reparseError(root, halign, false);
    if (stats && !stats.isDirectory()) throw new HalignError(".harness-align: expected a directory");
    if (!stats)
    {
        const legacy = join(root, ".halign");
        const legacyStats = await lstatIfExists(legacy);
        if (legacyStats)
        {
            assertContained(root, legacy, "legacy workspace");
            assertContained(root, halign, "workspace migration destination");
            await assertNoReparseTree(root, legacy);
            if (!legacyStats.isDirectory()) throw new HalignError(`${legacy}: expected a directory for migration`);
            await fs.rename(legacy, halign);
        }
    }
    await recoverSyncSources(root);
    const guidePath = join(halign, "AGENTS.md");
    await ensureRegularSource(root, guidePath);
    const guideStats = await lstatIfExists(guidePath);
    if (guideStats && !guideStats.isFile()) throw new HalignError(`${guidePath}: expected a regular workspace guide file`);
    const configPath = join(halign, "config.json");
    if (!(await lstatIfExists(configPath)))
    {
        await fs.mkdir(join(halign, "rules", "shared"), { recursive: true });
        await writeConfig(root, validateConfig(DEFAULT_USER_CONFIG));
    }
    if (!guideStats || (await fs.readFile(guidePath, "utf8")).startsWith(WORKSPACE_GUIDE_MARKER))
    {
        await atomicWrite(guidePath, Buffer.from(WORKSPACE_GUIDE, "utf8"));
    }
    return root;
}

/** Atomically write an already validated config document. */
async function writeConfig(root: string, config: Config): Promise<void>
{
    await writeManaged(root, ".harness-align/config.json", Buffer.from(`${JSON.stringify(configDocument(config), null, 2)}\n`, "utf8"));
}

/** Validate sources and atomically write `config.json`. */
export async function saveConfig(rootPath: string, config: Config): Promise<Config>
{
    const root = resolve(rootPath);
    const validated = validateConfig(configDocument(config));
    await Promise.all([loadLayerOptions(root, validated), loadRules(root, validated.harnesses), loadAgents(root, validated.harnesses)]);
    await writeConfig(root, validated);
    return validated;
}

/** Validate and atomically write a root rule. */
export async function saveRule(rootPath: string, input: RuleInput): Promise<void>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const path = managedRelative(input.path, input.path);
    const kind = ruleKind(path);
    if (kind === "shared") throw new HalignError(`${path}: shared rules are saved with saveSharedRule`);
    assertRulePath(path, kind);
    if (!Number.isInteger(input.priority) || input.priority < 0)
    {
        throw new HalignError(`${path}: priority must be a non-negative integer, got ${valueText(input.priority)}`);
    }
    const targets = validateTargets(input.targets, path, config.harnesses);
    await writeManaged(root, path, serializeFrontmatter({ priority: input.priority, targets }, input.body, path));
}

/** Validate and atomically write a layer option Markdown file. */
export async function saveLayerOption(rootPath: string, input: LayerOptionInput): Promise<void>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const path = managedRelative(input.path, input.path);
    const { layer } = layerOptionParts(path);
    const directory = join(root, ".harness-align", "layers", layer);
    await ensureRegularSource(root, directory);
    const stats = await lstatIfExists(directory);
    if (!stats?.isDirectory())
    {
        throw new HalignError(`${path}: layer does not exist, got ${valueText(layer)}`);
    }
    const targets = validateTargets(input.targets, path, config.harnesses);
    await writeManaged(root, path, serializeLayerOption(targets, input.body));
}

/** Validate and atomically write a shared-rule markdown file. */
export async function saveSharedRule(rootPath: string, path: string, body: string): Promise<void>
{
    const root = resolve(rootPath);
    const relative = managedRelative(path, path);
    assertRulePath(relative, "shared");
    await writeManaged(root, relative, Buffer.from(normalizedBody(body), "utf8"));
}

/** Validate and atomically write a subagent source file. */
export async function saveAgent(rootPath: string, agent: Agent): Promise<void>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const path = managedRelative(agent.path, agent.path);
    const next: Agent = { ...agent, path, body: normalizedBody(agent.body) };
    assertAgentInput(next, config.harnesses);
    const agents = await loadAgents(root, config.harnesses);
    const collision = agents.find((candidate) => candidate.name.toLowerCase() === next.name.toLowerCase() && pathKey(join(root, candidate.path)) !== pathKey(join(root, path)));
    if (collision) throw new HalignError(`${path}: name must be unique without case sensitivity, got ${valueText(next.name)} already used by ${collision.path}`);
    await writeManaged(root, path, serializeFrontmatter({
        name: next.name,
        description: next.description,
        harnesses: next.harnesses,
    }, next.body, path));
}

/** Delete a `.harness-align` source file after containment and reparse checks. */
export async function deleteSource(rootPath: string, relativePath: string): Promise<void>
{
    const root = resolve(rootPath);
    const relative = managedRelative(relativePath, relativePath);
    if (relative === ".harness-align/config.json") throw new HalignError(`${relative}: config.json cannot be deleted`);
    if (relative.startsWith(".harness-align/layers/")) throw new HalignError(`${relative}: layer options are deleted with removeLayerOption`);
    if (relative.startsWith(".harness-align/skills/")) throw new HalignError(`${relative}: skills are deleted with removeSkill`);
    const path = await resolveManaged(root, relative, relative);
    const stats = await lstatIfExists(path);
    if (!stats) throw new HalignError(`${relative}: file does not exist`);
    if (stats.isSymbolicLink()) throw reparseError(root, path, false);
    if (!stats.isFile()) throw new HalignError(`${relative}: managed source must be a file`);
    await fs.unlink(path);
}

/** Atomically move one rule or agent Markdown source within its source kind. */
export async function renameSource(rootPath: string, from: string, to: string): Promise<void>
{
    const root = resolve(rootPath);
    const sourceRelative = managedRelative(from, from);
    const destinationRelative = managedRelative(to, to);
    const sourceKind = editableSourceKind(sourceRelative);
    const destinationKind = editableSourceKind(destinationRelative);
    if (!sourceKind || sourceKind !== destinationKind)
    {
        throw new HalignError(`${from}: source rename must stay within one root-rule, shared-rule, or agent type, got ${valueText(to)}`);
    }
    if (sourceKind === "agent")
    {
        assertAgentPath(sourceRelative);
        assertAgentPath(destinationRelative);
    }
    else
    {
        assertRulePath(sourceRelative, sourceKind === "shared-rule" ? "shared" : "root");
        assertRulePath(destinationRelative, sourceKind === "shared-rule" ? "shared" : "root");
    }
    const source = await resolveManaged(root, sourceRelative, sourceRelative);
    const destination = await resolveManaged(root, destinationRelative, destinationRelative);
    const sourceStats = await lstatIfExists(source);
    if (!sourceStats) throw new HalignError(`${sourceRelative}: file does not exist`);
    if (sourceStats.isSymbolicLink()) throw reparseError(root, source, false);
    if (!sourceStats.isFile()) throw new HalignError(`${sourceRelative}: managed source must be a file`);
    await assertRenameDestination(source, destination, destinationRelative);
    await fs.rename(source, destination);
}

/** Create an empty catalog layer without adding it to the project selection. */
export async function addLayer(rootPath: string, name: string): Promise<Config>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const options = await loadLayerOptions(root, config);
    if (!IDENTIFIER_NAME.test(name)) throw new HalignError(`.harness-align/layers/${name}: layer name must match ${IDENTIFIER_NAME.source}, got ${valueText(name)}`);
    assertWindowsSafeName(name, `.harness-align/layers/${name}`);
    if (catalogHasFoldedName(options, name))
    {
        throw new HalignError(`.harness-align/layers/${name}: layer already exists, got ${valueText(name)}`);
    }
    const layersRoot = join(root, ".harness-align", "layers");
    const directory = join(layersRoot, name);
    await ensureRegularSource(root, directory);
    if (await lstatIfExists(directory)) throw new HalignError(`${display(root, directory)}: path already exists`);
    await fs.mkdir(layersRoot, { recursive: true });
    await fs.mkdir(directory);
    return config;
}

/** Remove a layer directory and drop it from the project selection when present. */
export async function removeLayer(rootPath: string, name: string): Promise<Config>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const options = await loadLayerOptions(root, config);
    if (!hasCatalogLayer(options, name))
    {
        throw new HalignError(`.harness-align/layers/${name}: layer does not exist, got ${valueText(name)}`);
    }
    const directory = join(root, ".harness-align", "layers", name);
    await assertNoReparseTree(root, directory);
    const temporary = join(root, ".harness-align", `.remove-layer-${name}-${process.pid}`);
    if (await lstatIfExists(temporary)) throw new HalignError(`${display(root, temporary)}: temporary path already exists`);
    const nextLayers = config.layers.filter((layer) => layer.name !== name);
    const next = nextLayers.length === config.layers.length
        ? config
        : validateConfig(configDocument({ ...config, layers: nextLayers }));
    await fs.rename(directory, temporary);
    try
    {
        if (next !== config) await writeConfig(root, next);
    }
    catch (error)
    {
        await fs.rename(temporary, directory);
        throw error;
    }
    await fs.rm(temporary, { recursive: true, force: true });
    return next;
}

/** Rename a layer directory and cascade its project selection when present. */
export async function renameLayer(rootPath: string, from: string, to: string): Promise<Config>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const options = await loadLayerOptions(root, config);
    if (!hasCatalogLayer(options, from)) throw new HalignError(`.harness-align/layers/${from}: layer does not exist, got ${valueText(from)}`);
    if (!IDENTIFIER_NAME.test(to)) throw new HalignError(`.harness-align/layers/${to}: layer name must match ${IDENTIFIER_NAME.source}, got ${valueText(to)}`);
    assertWindowsSafeName(to, `.harness-align/layers/${to}`);
    if (from.toLowerCase() !== to.toLowerCase() && catalogHasFoldedName(options, to))
    {
        throw new HalignError(`.harness-align/layers/${to}: layer names must be unique without case sensitivity, got ${valueText(to)}`);
    }
    const source = join(root, ".harness-align", "layers", from);
    const destination = join(root, ".harness-align", "layers", to);
    await ensureRegularSource(root, source);
    await ensureRegularSource(root, destination);
    await assertRenameDestination(source, destination, display(root, destination));
    const nextLayers = config.layers.map((layer) => (layer.name === from ? { ...layer, name: to } : layer));
    const next = nextLayers.some((layer, index) => layer !== config.layers[index])
        ? validateConfig(configDocument({ ...config, layers: nextLayers }))
        : config;
    if (source !== destination) await fs.rename(source, destination);
    try
    {
        if (next !== config) await writeConfig(root, next);
        return next;
    }
    catch (error)
    {
        if (source !== destination) await fs.rename(destination, source);
        throw error;
    }
}

/** Create an empty option file under an existing layer. */
export async function addLayerOption(rootPath: string, layer: string, option: string): Promise<void>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const options = await loadLayerOptions(root, config);
    if (!hasCatalogLayer(options, layer)) throw new HalignError(`.harness-align/layers/${layer}: layer does not exist, got ${valueText(layer)}`);
    if (!IDENTIFIER_NAME.test(option)) throw new HalignError(`layer option name must match ${IDENTIFIER_NAME.source}, got ${valueText(option)}`);
    assertWindowsSafeName(option, `layer option ${option}`);
    if (options[layer]!.some((candidate) => candidate.name.toLowerCase() === option.toLowerCase()))
    {
        throw new HalignError(`.harness-align/layers/${layer}: option already exists, got ${valueText(option)}`);
    }
    await writeManaged(root, `.harness-align/layers/${layer}/${option}.md`, Buffer.alloc(0));
}

/** Delete a non-selected layer option, allowing an unconfigured layer to become empty. */
export async function removeLayerOption(rootPath: string, layer: string, option: string): Promise<void>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const options = await loadLayerOptions(root, config);
    if (!hasCatalogLayer(options, layer)) throw new HalignError(`.harness-align/layers/${layer}: layer does not exist, got ${valueText(layer)}`);
    const layerConfig = config.layers.find((candidate) => candidate.name === layer);
    const layerOptions = options[layer]!;
    if (!layerOptions.some((candidate) => candidate.name === option)) throw new HalignError(`.harness-align/layers/${layer}: option does not exist, got ${valueText(option)}`);
    if (layerConfig?.selected === option) throw new HalignError(`.harness-align/config.json: selected layer option cannot be removed, got ${valueText(option)}`);
    const relative = `.harness-align/layers/${layer}/${option}.md`;
    const path = await resolveManaged(root, relative, relative);
    const stats = await lstatIfExists(path);
    if (!stats) throw new HalignError(`${relative}: file does not exist`);
    if (stats.isSymbolicLink()) throw reparseError(root, path, false);
    if (!stats.isFile()) throw new HalignError(`${relative}: managed source must be a file`);
    await fs.unlink(path);
}

/** Rename a layer option and cascade the saved selection when necessary. */
export async function renameLayerOption(rootPath: string, layer: string, from: string, to: string): Promise<Config>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const options = await loadLayerOptions(root, config);
    if (!hasCatalogLayer(options, layer)) throw new HalignError(`.harness-align/layers/${layer}: layer does not exist, got ${valueText(layer)}`);
    const layerConfig = config.layers.find((candidate) => candidate.name === layer);
    if (!options[layer]!.some((candidate) => candidate.name === from)) throw new HalignError(`.harness-align/layers/${layer}: option does not exist, got ${valueText(from)}`);
    if (!IDENTIFIER_NAME.test(to)) throw new HalignError(`layer option name must match ${IDENTIFIER_NAME.source}, got ${valueText(to)}`);
    assertWindowsSafeName(to, `layer option ${to}`);
    if (from.toLowerCase() !== to.toLowerCase() && options[layer]!.some((candidate) => candidate.name.toLowerCase() === to.toLowerCase()))
    {
        throw new HalignError(`.harness-align/layers/${layer}: option names must be unique without case sensitivity, got ${valueText(to)}`);
    }
    const source = join(root, ".harness-align", "layers", layer, `${from}.md`);
    const destination = join(root, ".harness-align", "layers", layer, `${to}.md`);
    await ensureRegularSource(root, source);
    await ensureRegularSource(root, destination);
    await assertRenameDestination(source, destination, display(root, destination));
    const next = validateConfig(configDocument({
        ...config,
        layers: config.layers.map((candidate) => candidate.name === layer && candidate.selected === from ? { ...candidate, selected: to } : candidate),
    }));
    if (source !== destination) await fs.rename(source, destination);
    try
    {
        if (layerConfig?.selected === from) await writeConfig(root, next);
        return next;
    }
    catch (error)
    {
        if (source !== destination) await fs.rename(destination, source);
        throw error;
    }
}

/** Replace a harness name inside a rule target list. */
function replaceHarnessName(targets: Harness[], from: string, to: string): Harness[]
{
    return targets.map((target) => (target === from ? to : target));
}

/** Update a harness and restore original sources if any cascaded write fails. */
export async function updateHarness(rootPath: string, from: string, harness: HarnessConfig): Promise<Config>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const existing = config.harnesses.find((candidate) => candidate.name === from);
    if (!existing)
    {
        throw new HalignError(`.harness-align/config.json: harness is not configured, got ${valueText(from)}`);
    }
    const nextConfig = validateConfig(configDocument({
        ...config,
        harnesses: config.harnesses.map((candidate) => (candidate.name === from ? harness : candidate)),
    }));
    const [rules, layerOptions, agents] = await Promise.all([
        loadRules(root, config.harnesses),
        loadLayerOptions(root, config),
        loadAgents(root, config.harnesses),
    ]);
    const nextRules = rules.map((rule) => ({ ...rule, targets: replaceHarnessName(rule.targets, from, harness.name) }));
    const nextLayerOptions = Object.values(layerOptions).flat().map((option) => ({ ...option, targets: replaceHarnessName(option.targets, from, harness.name) }));
    const nextAgents = agents.map((agent) =>
    {
        const harnesses: Record<string, Metadata> = {};
        for (const [name, metadata] of Object.entries(agent.harnesses))
        {
            harnesses[name === from ? harness.name : name] = metadata;
        }
        return { ...agent, harnesses };
    });
    const writes: Array<{ path: string; content: Buffer }> = [{
        path: ".harness-align/config.json",
        content: Buffer.from(`${JSON.stringify(configDocument(nextConfig), null, 2)}\n`, "utf8"),
    }];
    for (const rule of nextRules) validateTargets(rule.targets, rule.path, nextConfig.harnesses);
    for (const option of nextLayerOptions) validateTargets(option.targets, option.path, nextConfig.harnesses);
    for (const agent of nextAgents) assertAgentInput(agent, nextConfig.harnesses);
    if (from !== harness.name)
    {
        for (const rule of nextRules)
        {
            writes.push({ path: rule.path, content: serializeFrontmatter({ priority: rule.priority, targets: rule.targets }, rule.body, rule.path) });
        }
        for (const option of nextLayerOptions)
        {
            writes.push({ path: option.path, content: serializeLayerOption(option.targets, option.body) });
        }
        for (const agent of nextAgents)
        {
            writes.push({
                path: agent.path,
                content: serializeFrontmatter({ name: agent.name, description: agent.description, harnesses: agent.harnesses }, agent.body, agent.path),
            });
        }
    }
    await writeManagedBatch(root, writes);
    return nextConfig;
}

/** Remove a harness and cascade target allowlists plus agent metadata. */
export async function removeHarness(rootPath: string, name: string): Promise<void>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    if (!config.harnesses.some((harness) => harness.name === name))
    {
        throw new HalignError(`.harness-align/config.json: harness is not configured, got ${valueText(name)}`);
    }
    if (config.harnesses.length === 1)
    {
        throw new HalignError(`.harness-align/config.json: harnesses must be a non-empty mapping array, got []`);
    }
    const nextConfig: Config = { ...config, harnesses: config.harnesses.filter((harness) => harness.name !== name) };
    validateConfig(configDocument(nextConfig));
    const [rules, layerOptions, agents] = await Promise.all([
        loadRules(root, config.harnesses),
        loadLayerOptions(root, config),
        loadAgents(root, config.harnesses),
    ]);
    const nextRules: RuleInput[] = [];
    for (const rule of rules)
    {
        const targets = rule.targets.filter((target) => target !== name);
        nextRules.push({ ...rule, targets });
    }
    const nextLayerOptions: LayerOptionInput[] = [];
    for (const option of Object.values(layerOptions).flat())
    {
        const targets = option.targets.filter((target) => target !== name);
        nextLayerOptions.push({ ...option, targets });
    }
    const nextAgents: Agent[] = [];
    for (const agent of agents)
    {
        const harnesses = { ...agent.harnesses };
        delete harnesses[name];
        if (Object.keys(harnesses).length === 0)
        {
            throw new HalignError(`${agent.path}: at least one configured harness block is required`);
        }
        nextAgents.push({ ...agent, harnesses });
    }
    for (const agent of nextAgents) assertAgentInput(agent, nextConfig.harnesses);
    await writeManagedBatch(root, [
        { path: ".harness-align/config.json", content: Buffer.from(`${JSON.stringify(configDocument(nextConfig), null, 2)}\n`, "utf8") },
        ...nextRules.map((rule) => ({ path: rule.path, content: serializeFrontmatter({ priority: rule.priority, targets: rule.targets }, rule.body, rule.path) })),
        ...nextLayerOptions.map((option) => ({ path: option.path, content: serializeLayerOption(option.targets, option.body) })),
        ...nextAgents.map((agent) => ({ path: agent.path,
            content: serializeFrontmatter({ name: agent.name, description: agent.description, harnesses: agent.harnesses }, agent.body, agent.path) })),
    ]);
}

/** Add a harness declaration to config. */
export async function addHarness(rootPath: string, harness: HarnessConfig): Promise<Config>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    return saveConfig(root, { ...config, harnesses: [...config.harnesses, harness] });
}

/** Register a GitHub skill source URL in config. */
export async function addSkillSource(rootPath: string, input: { url: string; branch?: string }): Promise<Config>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const source = input.branch === undefined
        ? parseGitHubSkillSource(input.url)
        : parseGitHubSkillSource(input.url, input.branch);
    const key = `${source.owner.toLowerCase()}/${source.name.toLowerCase()}`;
    if (config.skillSources.some((item) => `${item.owner.toLowerCase()}/${item.name.toLowerCase()}` === key))
    {
        throw new HalignError(`.harness-align/config.json: skill_sources owner/name must be unique without case sensitivity, got ${valueText(`${source.owner}/${source.name}`)}`);
    }
    return saveConfig(root, { ...config, skillSources: [...config.skillSources, source] });
}

/** Remove a registered GitHub skill source from config. */
export async function removeSkillSource(rootPath: string, owner: string, name: string): Promise<Config>
{
    const root = resolve(rootPath);
    const config = await loadConfig(root);
    const nextSources = config.skillSources.filter((source) =>
        !(source.owner.toLowerCase() === owner.toLowerCase() && source.name.toLowerCase() === name.toLowerCase()));
    if (nextSources.length === config.skillSources.length)
    {
        throw new HalignError(`.harness-align/config.json: skill source is not configured, got ${valueText(`${owner}/${name}`)}`);
    }
    return saveConfig(root, { ...config, skillSources: nextSources });
}
