/**
 * Domain types used after Load has validated untrusted JSON and YAML.
 * Harness names come from config; this module does not keep a vendor-name union.
 */

/** Marker line written at the top of generated markdown files. */
export const MARKER = "<!-- Generated by Harness Align. Do not edit. -->";
/** Allowed subagent file stem. */
export const AGENT_NAME = /^[a-z0-9][a-z0-9_-]*$/u;
/** Allowed layer and option identifier. */
export const LAYER_NAME = /^[a-z0-9][a-z0-9_-]*$/u;
/** Allowed harness name. */
export const HARNESS_NAME = /^[a-z0-9][a-z0-9_-]*$/u;
/** Allowed subagent file extension without a leading dot. */
export const AGENT_EXTENSION = /^[a-z0-9][a-z0-9_-]*$/u;
/** ATX heading line outside fenced code. */
export const ATX_HEADING = /^( {0,3})(#{1,6})(?=[ \t]|$)/u;
/** Markdown fence opener. */
export const FENCE = /^ {0,3}(`{3,}|~{3,})/u;
/** Known rule frontmatter keys. */
export const RULE_FIELDS = new Set(["priority", "targets"]);
/** Known layer option frontmatter keys. */
export const LAYER_FIELDS = new Set(["targets"]);
/** Known subagent frontmatter keys. */
export const AGENT_FIELDS = new Set(["name", "description", "harnesses"]);
/** Known harness object keys in config.json. */
export const HARNESS_FIELDS = new Set(["name", "config_path", "agent_format", "agent_extension", "instructions_field"]);

/** Configured harness identifier. */
export type Harness = string;
/** Subagent serialization format. */
export type AgentFormat = "toml" | "yaml";
/** Untyped metadata mapping for one harness. */
export type Metadata = Record<string, unknown>;

/** One harness declared in `.halign/config.json`. */
export interface HarnessConfig
{
    name: Harness;
    configPath: string;
    agentFormat: AgentFormat;
    agentExtension: string;
    instructionsField?: string;
}

/** One ordered layer and its project-selected option. */
export interface LayerConfig
{
    name: string;
    selected: string;
}

/** One ordered layer choice used for a generation command. */
export interface LayerSelection
{
    name: string;
    option: string;
}

/** Validated `.halign/config.json` document. */
export interface Config
{
    version: 1;
    name: string;
    layers: LayerConfig[];
    harnesses: HarnessConfig[];
}

/** Loaded rule with validated frontmatter and markdown body. */
export interface Rule
{
    path: string;
    priority: number;
    targets: Harness[];
    body: string;
}

/** One selectable layer Markdown file with optional harness targeting. */
export interface LayerOption
{
    path: string;
    layer: string;
    name: string;
    targets: Harness[];
    body: string;
}

/** Loaded subagent with per-harness metadata and a shared markdown body. */
export interface Agent
{
    path: string;
    name: string;
    description: string;
    harnesses: Record<Harness, Metadata>;
    body: string;
}

/** Generated relative path to UTF-8 bytes. */
export type OutputMap = Map<string, Buffer>;

/** Domain error that the CLI reports as exit code 1. */
export class HalignError extends Error
{
    /** Create a domain error with a stable `HalignError` name. */
    constructor(message: string)
    {
        super(message);
        this.name = "HalignError";
    }
}

/** Convert an unknown thrown value into a printable message. */
export function errorText(error: unknown): string
{
    return error instanceof Error ? error.message : String(error);
}

/** Convert an unknown value into a JSON or fallback string for error text. */
export function valueText(value: unknown): string
{
    try
    {
        return JSON.stringify(value) ?? String(value);
    }
    catch
    {
        return String(value);
    }
}

/** Describe a JSON-like value kind for validation errors. */
export function typeText(value: unknown): string
{
    if (value === null) return "null";
    if (Array.isArray(value)) return "array";
    if (typeof value === "object") return "mapping";
    if (typeof value === "boolean") return "boolean";
    if (typeof value === "number" && Number.isInteger(value)) return "integer";
    return typeof value;
}

/** Return whether the value is a non-array object. */
export function isRecord(value: unknown): value is Record<string, unknown>
{
    return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Return whether `field` is an own property of `record`. */
export function hasOwn(record: Record<string, unknown>, field: string): boolean
{
    return Object.prototype.hasOwnProperty.call(record, field);
}

/** Compare two strings by Unicode code point for deterministic sorting. */
export function codePointCompare(left: string, right: string): number
{
    const leftPoints = Array.from(left, (character) => character.codePointAt(0) ?? 0);
    const rightPoints = Array.from(right, (character) => character.codePointAt(0) ?? 0);
    const length = Math.min(leftPoints.length, rightPoints.length);
    for (let index = 0; index < length; index += 1)
    {
        const difference = leftPoints[index]! - rightPoints[index]!;
        if (difference !== 0) return difference;
    }
    return leftPoints.length - rightPoints.length;
}

/** Return the first string in code-point order, or an empty string. */
export function firstSorted(values: Iterable<string>): string
{
    return [...values].sort(codePointCompare)[0] ?? "";
}

/** Normalize newlines to LF and ensure a single trailing newline. */
export function normalizedBody(body: string): string
{
    return `${body.replace(/\r\n?/gu, "\n").replace(/\n+$/u, "")}\n`;
}
