/**
 * Domain types used after Load has validated untrusted JSON and YAML.
 * Harness names come from config; this module does not keep a vendor-name union.
 */

/** Marker line written at the top of generated markdown files. */
export const MARKER = "<!-- Generated by Harness Align. Do not edit. -->";
/** Allowed case-preserving identifier for names, agent extensions, and instruction fields. */
export const IDENTIFIER_NAME = /^[A-Za-z0-9][A-Za-z0-9_-]*$/u;
/** Allowed skill directory identifier. */
export const SKILL_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]*$/u;
/** Maximum length of a skill directory identifier. */
export const SKILL_NAME_MAX = 128;
/** Known skill source object keys in config.json. */
export const SKILL_SOURCE_FIELDS = new Set(["owner", "name", "branch"]);
/** Windows reserved device names rejected as path segments. */
export const WINDOWS_RESERVED_NAMES = new Set([
    "CON", "PRN", "AUX", "NUL",
    "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9",
    "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9",
]);
/** ATX heading line outside fenced code. */
export const ATX_HEADING = /^( {0,3})(#{1,6})(?=[ \t]|$)/u;
/** Markdown fence opener. */
export const FENCE = /^ {0,3}(`{3,}|~{3,})/u;
/** YAML frontmatter fence at the start of a markdown file. */
export const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)(?:\r?\n)?/u;
/** Known rule frontmatter keys. */
export const RULE_FIELDS = new Set(["priority", "targets"]);
/** Known layer option frontmatter keys. */
export const LAYER_FIELDS = new Set(["targets"]);
/** Known subagent frontmatter keys. */
export const AGENT_FIELDS = new Set(["name", "description", "harnesses"]);
/** Known harness object keys in config.json. */
export const HARNESS_FIELDS = new Set(["name", "config_path", "agent_format", "agent_extension", "instructions_field"]);

/** Configured harness identifier. */
export type Harness = string;
/** Subagent serialization format. */
export type AgentFormat = "toml" | "yaml";
/** Untyped metadata mapping for one harness. */
export type Metadata = Record<string, unknown>;

/** One harness declared in `.harness-align/config.json`. */
export interface HarnessConfig
{
    name: Harness;
    configPath: string;
    agentFormat: AgentFormat;
    agentExtension: string;
    instructionsField?: string;
}

/** One ordered layer and its project-selected option. */
export interface LayerConfig
{
    name: string;
    selected: string;
}

/** One ordered layer choice used for a generation command. */
export interface LayerSelection
{
    name: string;
    option: string;
}

/** One registered GitHub skill repository source. */
export interface SkillSource
{
    owner: string;
    name: string;
    branch: string;
}

/** Validated `.harness-align/config.json` document. */
export interface Config
{
    version: 1;
    name: string;
    layers: LayerConfig[];
    harnesses: HarnessConfig[];
    skillSources: SkillSource[];
}

/** Provenance recorded for an installed project skill. */
export type SkillOrigin =
    | { kind: "github"; owner: string; name: string; branch: string; sourcePath: string; contentHash: string }
    | { kind: "local"; contentHash: string }
    | { kind: "unknown" };

/** Installed project skill metadata without file bodies. */
export interface ProjectSkill
{
    id: string;
    title: string;
    description: string;
    origin: SkillOrigin;
}

/** Skill discovered under the user profile skills directory. */
export interface UserSkill
{
    id: string;
    title: string;
    description: string;
}

/** Loaded rule with validated frontmatter and markdown body. */
export interface Rule
{
    path: string;
    priority: number;
    targets: Harness[];
    body: string;
}

/** One selectable layer Markdown file with optional harness targeting. */
export interface LayerOption
{
    path: string;
    layer: string;
    name: string;
    targets: Harness[];
    body: string;
}

/** Loaded subagent with per-harness metadata and a shared markdown body. */
export interface Agent
{
    path: string;
    name: string;
    description: string;
    harnesses: Record<Harness, Metadata>;
    body: string;
}

/** Generated relative path to UTF-8 bytes. */
export type OutputMap = Map<string, Buffer>;

/** Domain error reported by the desktop application. */
export class HalignError extends Error
{
    /** Create a domain error with a stable `HalignError` name. */
    constructor(message: string)
    {
        super(message);
        this.name = "HalignError";
    }
}

/** Convert an unknown thrown value into a printable message. */
export function errorText(error: unknown): string
{
    return error instanceof Error ? error.message : String(error);
}

/** Convert an unknown value into a JSON or fallback string for error text. */
export function valueText(value: unknown): string
{
    try
    {
        return JSON.stringify(value) ?? String(value);
    }
    catch
    {
        return String(value);
    }
}

/** Return whether `name` is a Windows reserved device name such as `con` or `lpt1`. */
export function isWindowsReservedName(name: string): boolean
{
    return WINDOWS_RESERVED_NAMES.has(name.toUpperCase());
}

/** Throw if `name` cannot be used as a Windows directory or file stem. */
export function assertWindowsSafeName(name: string, context: string): void
{
    if (isWindowsReservedName(name.split(".")[0] ?? name))
    {
        throw new HalignError(`${context}: name must not be a Windows reserved device name, got ${valueText(name)}`);
    }
    if (!name || /[<>:"/\\|?*]/u.test(name) || /[. ]$/u.test(name) || [...name].some((character) => character.charCodeAt(0) < 32))
    {
        throw new HalignError(`${context}: name must be a Windows-safe path segment without trailing dots or spaces, got ${valueText(name)}`);
    }
}

/** Describe a JSON-like value kind for validation errors. */
export function typeText(value: unknown): string
{
    if (value === null) return "null";
    if (Array.isArray(value)) return "array";
    if (typeof value === "object") return "mapping";
    if (typeof value === "boolean") return "boolean";
    if (typeof value === "number" && Number.isInteger(value)) return "integer";
    return typeof value;
}

/** Return whether the value is a non-array object. */
export function isRecord(value: unknown): value is Record<string, unknown>
{
    return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Return whether `field` is an own property of `record`. */
export function hasOwn(record: Record<string, unknown>, field: string): boolean
{
    return Object.prototype.hasOwnProperty.call(record, field);
}

/** Compare two strings by Unicode code point for deterministic sorting. */
export function codePointCompare(left: string, right: string): number
{
    if (left === right) return 0;
    const leftIterator = left[Symbol.iterator]();
    const rightIterator = right[Symbol.iterator]();
    for (;;)
    {
        const leftNext = leftIterator.next();
        const rightNext = rightIterator.next();
        if (leftNext.done === true && rightNext.done === true) return 0;
        if (leftNext.done === true) return -1;
        if (rightNext.done === true) return 1;
        const difference = (leftNext.value.codePointAt(0) ?? 0) - (rightNext.value.codePointAt(0) ?? 0);
        if (difference !== 0) return difference;
    }
}

/** Return the first string in code-point order, or an empty string. */
export function firstSorted(values: Iterable<string>): string
{
    return [...values].sort(codePointCompare)[0] ?? "";
}

/** Normalize newlines to LF and ensure a single trailing newline. */
export function normalizedBody(body: string): string
{
    return `${body.replace(/\r\n?/gu, "\n").replace(/\n+$/u, "")}\n`;
}
