/*
领域模型与共享基础:

- 类型只存在于编译期. JSON/YAML 输入必须经 load 模块显式验证后, 才能成为这里的 `Config`, `Rule`, `Agent`.
- Harness 名称来自已验证配置, 生产代码不保留厂商名称 union.
*/

export const MARKER = "<!-- Generated by Harness Align. Do not edit. -->";
export const AGENT_NAME = /^[a-z0-9][a-z0-9_-]*$/u;
export const HARNESS_NAME = /^[a-z0-9][a-z0-9_-]*$/u;
export const AGENT_EXTENSION = /^[a-z0-9][a-z0-9_-]*$/u;
export const ATX_HEADING = /^( {0,3})(#{1,6})(?=[ \t]|$)/u;
export const FENCE = /^ {0,3}(`{3,}|~{3,})/u;
export const RULE_FIELDS = new Set(["priority", "targets"]);
export const AGENT_FIELDS = new Set(["name", "description", "harnesses"]);
export const HARNESS_FIELDS = new Set(["name", "config_path", "agent_format", "agent_extension", "instructions_field"]);

export type Harness = string;
export type AgentFormat = "toml" | "yaml";
// `Record<string, unknown>` 表示字符串键到未知值的静态映射. 它不是运行时 Dictionary, 也不保证值真是普通对象.
export type Metadata = Record<string, unknown>;

export interface HarnessConfig
{
    name: Harness;
    configPath: string;
    agentFormat: AgentFormat;
    agentExtension: string;
    instructionsField?: string;
}

export interface Config
{
    version: 2;
    name: string;
    defaultProfile: string;
    profiles: string[];
    harnesses: HarnessConfig[];
}

export interface Rule
{
    path: string;
    priority: number;
    targets: Harness[];
    body: string;
}

export interface Agent
{
    path: string;
    name: string;
    description: string;
    harnesses: Record<Harness, Metadata>;
    body: string;
}

// `Map` 保留插入顺序且键不被隐式转换. `Buffer` 是 Node 的二进制容器, renderer 在此固定 UTF-8 bytes.
export type OutputMap = Map<string, Buffer>;

// 少数需要在运行时辨认的类型, 因而使用 class. CLI 只把预期错误格式化为稳定错误码.
export class HalignError extends Error
{
    constructor(message: string)
    {
        super(message);
        this.name = "HalignError";
    }
}

// catch 值是 `unknown`, 不能假定存在 `.message`.
export function errorText(error: unknown): string
{
    return error instanceof Error ? error.message : String(error);
}

export function valueText(value: unknown): string
{
    try
    {
        return JSON.stringify(value) ?? String(value);
    }
    catch
    {
        return String(value);
    }
}

export function typeText(value: unknown): string
{
    if (value === null) return "null";
    if (Array.isArray(value)) return "array";
    if (typeof value === "object") return "mapping";
    if (typeof value === "boolean") return "boolean";
    if (typeof value === "number" && Number.isInteger(value)) return "integer";
    return typeof value;
}

// type guard 的 `value is ...` 同时包含运行时检查和编译器提示.
export function isRecord(value: unknown): value is Record<string, unknown>
{
    return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function hasOwn(record: Record<string, unknown>, field: string): boolean
{
    return Object.prototype.hasOwnProperty.call(record, field);
}

// 显式按 Unicode code point 比较, 以换取跨 Node 环境可复现的输出和错误顺序.
export function codePointCompare(left: string, right: string): number
{
    const leftPoints = Array.from(left, (character) => character.codePointAt(0) ?? 0);
    const rightPoints = Array.from(right, (character) => character.codePointAt(0) ?? 0);
    const length = Math.min(leftPoints.length, rightPoints.length);
    for (let index = 0; index < length; index += 1)
    {
        const difference = leftPoints[index]! - rightPoints[index]!;
        if (difference !== 0) return difference;
    }
    return leftPoints.length - rightPoints.length;
}

export function firstSorted(values: Iterable<string>): string
{
    return [...values].sort(codePointCompare)[0] ?? "";
}

// canonical bytes: 统一 CRLF/CR 为 LF, 再保证恰好一个结尾换行.
export function normalizedBody(body: string): string
{
    return `${body.replace(/\r\n?/gu, "\n").replace(/\n+$/u, "")}\n`;
}
